apiVersion: v1
baseDomain: sandbox230.opentlc.com
compute:
- hyperthreading: Enabled
  name: worker
  platform: 
    aws:
      type: m5.xlarge
  replicas: 4
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  name: cluster-a1c2
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-west-2
pullSecret: | 
  ${pull_secret}
sshKey: |
  ${ssh_key}
  