apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: amq
spec:
  deploymentPlan:
    requireLogin: false
    size: 2
    image: registry.redhat.io/amq7/amq-broker:7.7
  adminUser: admin
  adminPassword: admin
  console:
    expose: true
    sslEnabled: true
    #sslSecret: amq-console-tls    
  acceptors:
  - name: amqp-tls
    protocols: amqp
    port: 5671
    sslEnabled: true
    #sslSecret: amqp-tls
    expose: false
    verifyHost: false
    connectionsAllowed: 25
  - name: amqp
    protocols: amqp
    port: 5672
    sslEnabled: false
    #sslSecret: amqp-tls
    expose: false
    verifyHost: false
    connectionsAllowed: 25    
---
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: myaddress
spec:
  addressName: myqueue
  queueName: myqueue
  routingType: anycast  
        