---  
apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: router-mesh
spec:
  deploymentPlan:
    role: interior  
    size: 2  
    placement: AntiAffinity
  addresses:
  - prefix: myqueue  
    waypoint: true
  autoLinks:  
  - address: myqueue
    direction: in
    connection: amq-0
  - address: myqueue
    direction: out
    connection: amq-0
  - address: myqueue
    direction: in
    connection: amq-1
  - address: myqueue
    direction: out
    connection: amq-1  
  connectors:  
  - name: amq-0
    host: amq-ss-0.amq-hdls-svc
    port: 5671
    routeContainer: true
    sslProfile: amq-tls
  - name: amq-1
    host: amq-ss-1.amq-hdls-svc
    port: 5671
    routeContainer: true
    sslProfile: amq-tls    
  interRouterListeners:  
  - authenticatePeer: true
    expose: false
    port: 55671
    saslMechanisms: EXTERNAL
    sslProfile: inter-router    
  sslProfiles:
  - name: amq-tls
    caCert: amq-amqp-mesh-client-tls-secret
    generateCredentials: false
  - name: default
    credentials: router-mesh-tls
    generateCredentials: false
  - name: inter-router
    caCert: inter-router-mesh-tls
    credentials: inter-router-mesh-tls
    mutualAuth: true
    generateCredentials: false            
  listeners:
  # - port: 5672
  - authenticatePeer: false
    expose: true
    http: true
    port: 8443
    sslProfile: default
  - port: 5671
    sslProfile: default
    expose: true
  users: router-mesh-users