---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: router-mesh-tls
spec:
  # Secret names are always required.
  secretName: router-mesh-tls
  commonName: router-mesh-tls
  usages:
    - server auth
  dnsNames:
  - router-mesh
  - router-mesh.amq.svc
  - router-mesh.amq.svc.cluster.local
  - router-mesh-5671-amq.apps.${base_domain}
  - router-mesh-8443-amq.apps.${base_domain}
  duration: 168h
  renewBefore: 1h
  issuerRef:
    name: internal-issuer
  keystores:  
    jks:
      create: true
      passwordSecretRef:
        name: router-mesh-tls
        key: keyStorePassword     
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inter-router-mesh-tls
spec:
  # Secret names are always required.
  secretName: inter-router-mesh-tls
  commonName: inter-router-mesh-tls
  usages:
    - server auth
    - client auth
  dnsNames:
  - router-mesh
  - router-mesh.amq.svc
  - router-mesh.amq.svc.cluster.local
  duration: 168h
  renewBefore: 1h
  issuerRef:
    name: internal-issuer   
---
apiVersion: v1
kind: Secret
metadata:
  name: amq-amqp-mesh-client-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: router-mesh-tls
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
stringData:
  keyStorePassword: changeit
  trustStorePassword: changeit  
